Controllers/RevendeurCommandeController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MiniProjet_.NET.Models;
using MiniProjet_.NET.Models.Repositories;
using Net.Codecrete.QrCodeGenerator;
using System.Globalization;

namespace MiniProjet_.NET.Controllers
{
    public class RevendeurCommandeController : Controller
    {
        //Injection de la dépendance
        readonly IRevendeurCommandeRepository RevendeurCommandeRepository;
        readonly IDetailCommandeRepository DetailCommandeRepository;
        readonly IArticleRepository ArticleRepository;
        readonly IVariationRepository VariationRepository;
        private readonly UserManager<ApplicationUser> userManager;
        private readonly IWebHostEnvironment hostingEnvironment;

        public RevendeurCommandeController(IRevendeurCommandeRepository RevendeurCommandeRepository, IWebHostEnvironment hostingEnvironment,
                 UserManager<ApplicationUser> userManager, IDetailCommandeRepository DetailCommandeRepository, IArticleRepository articleRepository,
                 IVariationRepository variationRepository
                 )
        {
            this.RevendeurCommandeRepository = RevendeurCommandeRepository;
            this.DetailCommandeRepository = DetailCommandeRepository;
            ArticleRepository = articleRepository;
            VariationRepository = variationRepository;
            this.hostingEnvironment = hostingEnvironment;
            this.userManager = userManager;
        }

        public string GenerateSerieNumber()
        {
            var rand = new Random();
            string serialNumber;
            while (true)
            {
                serialNumber = "";

                for (int i = 0; i < 13; i++)
                {
                    serialNumber += rand.Next(0, 10).ToString();
                }

                var article = ArticleRepository.GetArticleBySerieNumber(serialNumber);

                if (article == null)
                {
                    break;
                }
            }

            return serialNumber;
        }

        public void GenerateQrCode(string serieNumber, string designation)
        {
            // Encode the text to a QR code
            var qr = QrCode.EncodeText(serieNumber, QrCode.Ecc.Medium);

            // Convert the QR code to SVG string
            string svg = qr.ToSvgString(4);


            // Specify the folder to save the QR code SVG file
            string uploadsFolder = Path.Combine(hostingEnvironment.WebRootPath, $"QrCodes/Articles/{designation}");
            if (!Directory.Exists(uploadsFolder))
            {
                Directory.CreateDirectory(uploadsFolder);
            }
            // Ensure the folder exists
            Directory.CreateDirectory(uploadsFolder);

            // Specify the file path
            string uniqueFileName = $"{serieNumber}_serieNumber.svg";
            string filePath = Path.Combine(uploadsFolder, uniqueFileName);

            // Save the SVG content to the file
            System.IO.File.WriteAllText(filePath, svg);
        }


        // GET: RevendeurCommandeController
        public ActionResult Index()
        {
            var revendeurCommandes = RevendeurCommandeRepository.GetRevendeurCommandes();
           
            return View(revendeurCommandes);
        }

        // GET: RevendeurCommandeController/Details/5
        public ActionResult Details(int id)
        {
            var revendeurCommande = RevendeurCommandeRepository.GetRevendeurCommande(id);
            var detailsCommande = DetailCommandeRepository.GetDetailCommandeRevendeursByCommandeId(id);
            var ariclesCommande = ArticleRepository.GetArticlesByRevendeurAndCommande(revendeurCommande.RevendeurId, revendeurCommande.Id);
            
                Console.WriteLine(detailsCommande.ToString());
            
            var model = (revendeurCommande, detailsCommande, ariclesCommande);
            return View(model);
        }

        // GET: RevendeurCommandeController/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: RevendeurCommandeController/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(IFormCollection collection)
        {
            var series = collection["series[]"];
            var prices = collection["prices[]"];
            var quantities = collection["quantities[]"];
            var sous_totals = collection["sous_totals[]"];
            var revendeurId = collection["revendeur"];

            //parsing de total
            
            var culture = new CultureInfo("en-US");
            decimal total = decimal.Parse(collection["total"], culture);

            var revendeur = await userManager.FindByIdAsync(revendeurId);
            // save commande
            var nbCmdsRevendeur = RevendeurCommandeRepository.GetRevendeurCommandesByRevendeurId(revendeurId).Count();
            nbCmdsRevendeur++; // update to the new number of commands
            RevendeurCommande revendeurCommande = new RevendeurCommande
            {
                Total = total,
                Reference = revendeur.NormalizedUserName.Substring(0, 4) +"x"+ DateTime.Now.ToString("yyyyMMdd")+"x"+nbCmdsRevendeur.ToString(),
                RevendeurId = revendeurId
              
            };
            RevendeurCommandeRepository.AddRevendeurCommande(revendeurCommande);
            
            // save details commande
            for (int i=0; i<series.Count(); i++)
            {
                var serie = VariationRepository.GetVariationByDesignation(series[i]);
                decimal sous_total = decimal.Parse(sous_totals[i], culture);
                decimal prix = decimal.Parse(prices[i], culture);
                DetailCommandeRevendeur detailCommandeRevendeur = new DetailCommandeRevendeur
                {
                    VariationId = serie.Id,
                    Qte = int.Parse(quantities[i]),
                    SousTotal = sous_total,
                    Prix = prix,
                    RevendeurCommandeId = revendeurCommande.Id,
                    
                };
                DetailCommandeRepository.AddDetailCommandeRevendeur(detailCommandeRevendeur);

                var articlesNonAchetes = ArticleRepository.GetArticlesByStatusAndVariationId(false, serie.Id); 

                int j = 0;
                foreach (var article in articlesNonAchetes)
                {
                    if (j == int.Parse(quantities[i]))
                    {
                        break;
                    }

                    article.Status = true;
                    article.RevendeurId = revendeurId;
                    article.RevendeurCommandId = revendeurCommande.Id;
                    ArticleRepository.UpdateArticle(article);

                    j++;
                }

                //in case there was not enough quantities
                for (; j < int.Parse(quantities[i]); j++)
                {
                    var serieNumber = GenerateSerieNumber();
                    Article newArticle = new()
                    {
                        SerieNumber = serieNumber,
                        Status = true,
                        VariationId = serie.Id,
                        RevendeurId = revendeurId,
                        RevendeurCommandId = revendeurCommande.Id
                    };
                    ArticleRepository.AddArticle(newArticle);
                    GenerateQrCode(serieNumber, serie.Designation);
                }

            }

            return RedirectToAction(nameof(Index));
            
        }

        // GET: RevendeurCommandeController/Edit/5
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: RevendeurCommandeController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }

        // GET: RevendeurCommandeController/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: RevendeurCommandeController/Delete/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Delete(int id, IFormCollection collection)
        {
            try
            {
                return RedirectToAction(nameof(Index));
            }
            catch
            {
                return View();
            }
        }
    }
}

Views/RevendeurCommande/Details.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> userManager

@model (RevendeurCommande commande, IEnumerable<DetailCommandeRevendeur> detailCommandeRevendeurs, IEnumerable<Article> articles)

<div>

    <div class="card">
        <div class="card-body">
            <div class="ml-4">
                <div class="row">
                    <div class="col-6">
                        <p> Commande n° <b> @Model.commande.Reference  </b> </p>
                    </div>
                    <div class="col-6">
                        <p> Date de la commande: @Model.commande.UpdatedAt </b> </p>
                    </div>
                </div>
                <div class="row">
                    <div class="col-6">
                        <p> Nom du revendeur: <b> @( userManager.FindByIdAsync(Model.commande.RevendeurId)?.Result.NormalizedUserName) </b> </p>
                    </div>
                    <div class="col-6">
                        <p> Email du revendeur: <b>@( userManager.FindByIdAsync(Model.commande.RevendeurId)?.Result.Email)</b> </p>
                    </div>
                </div>
                
            </div>

            <h3 class="text-center my-4"> Détails de la commande </h3>

            <div class="row clearfix">
                <div class="col-lg-12">
                    <div class="card">
                        <div class="card-body">
                            <div class="panier">
                                <div class="table-responsive">
                                    <table class="table table-hover table-vcenter table-striped" cellspacing="0">
                                        <thead>
                                            <tr>
                                                <th>Référence </th>
                                                <th>Désignation</th>
                                                <th>Prix</th>
                                                <th>Quantité</th>
                                                <th>Sous-total</th>
                                            </tr>
                                        </thead>

                                        <tfoot>
                                            <hr>
                                            <tr>
                                                <td colspan="4" class="text-right"><b>Total</b></td>
                                                <td>
                                                    <b id="total">@Model.commande.Total</b> <small> DT </small>
                                                </td>
                                            </tr>

                                        </tfoot>

                                        <tbody id="cart-table">
                                            @foreach (var detailsCommande in Model.detailCommandeRevendeurs)
                                            {
                                                <tr class="cart_row bg-white border-b border-gray-700">
                                                    <td><b>@Model.commande.Reference</b> </td>
                                                    <td><b>@detailsCommande.Variation.Designation</b> </td>
                                                    <td class="prix">@detailsCommande.Prix</td>
                                                    <td class="qte">@detailsCommande.Qte</td>
                                                    <td class="sout_total"><b>@detailsCommande.SousTotal</b></td>
                                                </tr>
                                            }
                                           
                                          
                                        </tbody>


                                    </table>
                                </div>
                            </div>
                        </div>
                    </div>

                </div>
            </div>

        </div>
        <div class="my-4">
            <p class="text-right mr-4"> Reçu en <b>@DateTime.Now.ToString()</b> </p>
        </div>
    </div>
</div>
    <div class="d-flex justify-content-center">
        <div class="return-btn-label d-flex">
            <small class="mt-2"> Si vous avez terminé, </small>
            <a asp-action="Index" asp-controller="RevendeurCommande" class="btn btn-link">
                <small class="return-btn-label">retourner vers la liste des commandes </small> </a>
        </div> <span class="rotative-icon mt-1 mr-4"><i class="fe fe-rotate-cw"></i></span>

        <button type="button" id="print-commande-btn" class="btn btn-success checkout-btn" title="Impression d'un reçu"
            data-toggle="tooltip" data-placement="bottom">
            <i class="icon-printer mr-2"></i>Imprimer Reçu
        </button>
        <button type="button" id="print-commande-qrs-btn" class="btn btn-indigo" title="Impression d'un reçu"
            data-toggle="tooltip" data-placement="bottom">
            <i class="icon-printer mr-2"></i>Imprimer Qrs
        </button>
    </div>
    <script>
        var leftSidebarID = "left-sidebar-menu-commandes-revendeurs";
    </script>



<div id="pdf-content" style="display:none">
    <br><br><br>
    <div class="card">
        <div class="card-body">
            <table cellspacing="10">
                <tr>
                    <td>
                        <p> Commande n° <b>@Model.commande.Reference  </b> </p>
                    </td>
                    <td></td>
                    <td>
                        <p> Date de la commande:  @Model.commande.UpdatedAt</b> </p>
                    </td>
                </tr>
                <tr>
                    <td>
                        <p> Nom du revendeur: <b> @( userManager.FindByIdAsync(Model.commande.RevendeurId)?.Result.NormalizedUserName)</b> </p>
                    </td>
                    <td></td>
                    <td>
                        <p> Email du revendeur: <b>@( userManager.FindByIdAsync(Model.commande.RevendeurId)?.Result.Email)</b> </p>
                    </td>
                </tr>
               
            </table>
            <br><br><br>
            <br><br><br>
            <h3 align="center">
                Détails de la commande
            </h3>

            <br> <br>
            <table class="table table-hover table-vcenter table-striped" cellspacing="20">
                <thead>
                    <tr>
                        <th colspan="2">Référence </th>
                        <th colspan="2">Désignation</th>
                        <th colspan="2">Prix</th>
                        <th colspan="2">Quantité</th>
                        <th colspan="2">Sous-total</th>
                    </tr>

                </thead>

                <tfoot>
                    <hr>
                    <tr>
                        <td colspan="8" ><b align="right">Total</b></td>
                        <td><b id="total">@Model.commande.Total</b> <small> DT </small>
                        </td>
                    </tr>

                </tfoot>

                <tbody id="cart-table">
                    @foreach (var detailsCommande in Model.detailCommandeRevendeurs)
                    {
                        <tr class="cart_row bg-white border-b border-gray-700">
                        <td colspan="2"><b>@Model.commande.Reference</b> </td>
                        <td colspan="2"><b>@detailsCommande.Variation.Designation</b> </td>
                        <td colspan="2" class="prix">@detailsCommande.Prix</td>
                        <td colspan="2" class="qte">@detailsCommande.Qte</td>
                        <td colspan="2" class="sout_total"><b>@detailsCommande.SousTotal</b></td>
                        </tr>
                    }
                </tbody>


            </table>


        </div>
        <br>
        <br>
        <p align="right"> Reçu en <b>@DateTime.Now.ToString()</b> </p>

    </div>
</div>

    <div class="card " id="pdf-qrs-content" style="display:none">
        <div class="card-body">
            <table>
                <thead>

                </thead>


                <tbody>
                    @{
                    int i = 0; 

                    foreach (var article in Model.articles)
                    {
                        if (i % 3 == 0)
                        {
                            @:</tr><tr>
                        }

                        <td>
                            <table>
                                <tr>
                                    <td align="center"><b>@article.SerieNumber</b></td>
                                </tr>
                                <tr>
                                    <td>
                                        <img src="@Url.Content($"~/QrCodes/Articles/{article.Variation.Designation}/{article.SerieNumber}_serieNumber.svg")" class="qr_code" width="230">
                                    </td>
                                </tr>
                            </table>
                        </td>

                        i++;
                    }
                }

                </tbody>
                </table>
        </div>
    </div>

Views/RevendeurCommande/Index.cshtml
@using Microsoft.AspNetCore.Identity
@inject UserManager<ApplicationUser> userManager

@model IEnumerable<RevendeurCommande>


<h4 class="text-center"> List des commandes des revendeurs</h4>
    <div class="card">
        <div class="card-body">
            <div class="section-body">
                <div class="container-fluid">
                    <div class="row clearfix">
                        <div class="col-lg-12">
                            <div class="table-responsive mb-4">
                                <table class="table table-hover commandes-rev-data-table dataTable table_custom spacing5">
                                    <thead>
                                        <tr>
                                            <th>Reference</th>
                                            <th>Revendeur</th>
                                            <th>Prix Total</th>
                                            <th>Date Vente</th>
                                            <th></th>
                                        </tr>
                                    </thead>
                                    <tfoot>
                                        <tr>
                                            <th>Reference</th>
                                            <th>Revendeur</th>
                                            <th>Prix Total</th>
                                            <th>Date Vente</th>
                                            <th></th>
                                        </tr>
                                    </tfoot>
                                    <tbody>
                                    @foreach (var cmd in Model)
                                    {
                                        <tr class="curr-commande">
                                            <td class="reference"> @cmd.Reference </td>
                                            <td class="username"> @(await userManager.FindByIdAsync(cmd.RevendeurId))  </td>
                                            <td class="total"> @cmd.Total </td>
                                            <td class="date"> @cmd.CreatedAt </td>
                                            <td>
                                                <a asp-action="Details" asp-controller="RevendeurCommande" asp-route-id="@cmd.Id"
                                                   class="view-more-commande" title="En-savoir plus"
                                                   data-toggle="tooltip" data-placement="top">
                                                    <i class="icon-eye"></i>
                                                </a>
                                            </td>
                                        </tr>
                                    }
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <script>
        var leftSidebarID = "left-sidebar-menu-commandes-revendeurs";
    </script>